### PR TITLE
course update

### PR DESCRIPTION
**Pull request by KadeStyron**
I updated course.java to include bulletin variables

### CODE REVIEW

**Review by cooperbocko — COMMENTED** [review]
all that should have been added to course.java is this information from bulletin: <head></head>
Course ID: | CSCI 1100-1100L. 3 hours. 2 hours lecture and 2 hours lab per week.
-- | --
Course Title: | Topics in Computing
CourseDescription: | Fundamental concepts of computing and information science and their application to everyday computer use. Topics include data representation, addressing and mapping, network protocols, standards, data exchange, encryption and security, mathematical modeling, and data modeling. Hands-on labs emphasize problem-solving using software to collect and analyze data, and evaluate and present results.
Athena Title: | Topics in Computing
Semester CourseOffered: | Offered fall and spring semester every year.
Grading System: | A-F (Traditional)

**Comment by cooperbocko** [comment]
ok that is a weird format but I will explain tomorrow at the dev session

**Comment by KadeStyron** [comment]
Ok, my bad I just used everything from the design thing.

**Review by cooperbocko — APPROVED** [review]
nice!

**Pull request merged**
