### PR TITLE
Created relationships between class, course, and section for issue #166

### PR DESCRIPTION
**Pull request by MollySohaney**

### CODE REVIEW

**Review by cooperbocko — CHANGES_REQUESTED** [review]
Can you go and put the annotations for the relationships as well?

**Comment by MollySohaney** [comment]
Done

**Review by cooperbocko — COMMENTED** [review]
Can you add to constructors and create getters and setters for what you added? Besides that it looks great!

**Comment by MollySohaney** [comment]
For the constructor, do I add the whole object (ex. course) or just the attribute that is listed in the diagram (ex. courseID)?

**Review by cooperbocko — APPROVED** [review]

**Comment by cooperbocko** [comment]
> For the constructor, do I add the whole object (ex. course) or just the attribute that is listed in the diagram (ex. courseID)?

You should add the whole object

**Comment by MollySohaney** [comment]
Done. Let me know, if I have to do anything else.

**Pull request closed without merging**
