### PR TITLE
added the comment class for ratemyprofesor

### PR DESCRIPTION
**Pull request by seeus00**
added the comment class for ratemyprofesor

### CODE REVIEW

**Review by Jeffrey-000 — CHANGES_REQUESTED** [review]
just to be consistent with coding conventions used across the whole project please add javadoc comments to all the methods

**Comment by seeus00** [comment]
added javadoc to all methods

**Comment by IgnasPanavas** [comment]
For now let's place the web scraping related files within the related microservice using the project structure microservice_name/src/main/(package name)/webscraping. The web scraping folder needs to be created. Also please re fetch as there have been changes to dev since the pull was requested.

**Comment by seeus00** [comment]
Moved comment class to new directory

**Comment by IgnasPanavas** [comment]
Still Jeffrey's issue, he'll take care of closing and merging

**Pull request merged**
