### PR TITLE
Issue 58 - added GET endpoint for aggregate professor difficulty

### PR DESCRIPTION
**Pull request by YatinKare**
- Added the GET endpoint for an aggregate professor difficulty rating that returns an arbitrary value (for now).

### CODE REVIEW

**Comment by IgnasPanavas** [comment]
Can you pull the repo and update your code to fit with the new code. I merged some pull requests before I got a chance to merge this so the file is a bit out of date.

**Review by IgnasPanavas — CHANGES_REQUESTED** [review]
Pull the new changes and add your implementation to that so that your code fits within the current code base.

**Comment by YatinKare** [comment]
Could you check if everything is good now? Sorry fo the delay.

**Comment by IgnasPanavas** [comment]
I updated the expected format for all endpoints. Take a look at the changes in the Bulletin controller for what I'm looking them all to look like in the future. I'm adding time to this issue and all others to implement those changes. Thanks.

**Comment by DogeDevYT** [comment]
obsolete, closing

**Pull request closed without merging**
