### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sebswU**
Move config Bean objects to one java file (CourseInformationApplication.java) and delete respective config files (CourseRepository, CourseSection)
solves issue: Move configs to one file #215

I know there are some missing repository definitions (Building, CourseSection), so if you need me to change this file (CourseInformationApplication.java) accordingly please let me know.

### CODE REVIEW

**Review by cooperbocko — COMMENTED** [review]
All you need is one Commandline running with the bean annotation, and then you just create each new class in them

**Comment by cooperbocko** [comment]
Also could you try and remove the random file changes you also have, it might not be necessary but I am trying to figure out why they pop up

**Comment by sebswU** [comment]
when you say random file changes do you mean the created json config files?

**Review by cooperbocko — APPROVED** [review]
looks good!

**Pull request merged**
